name: Build and Deploy Preview
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install
      - name: Create .env
        run: |
          touch .env
          echo SNOWPACK_PUBLIC_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}>>.env
          echo SNOWPACK_PUBLIC_FIREBASE_AUTH_DOMAIN=freshy-the-journey.firebaseapp.com>>.env
          echo SNOWPACK_PUBLIC_FIREBASE_PROJECT_ID=freshy-the-journey>>.env
          echo SNOWPACK_PUBLIC_FIREBASE_STORAGE_BUCKET=freshy-the-journey.appspot.com>>.env
          echo SNOWPACK_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}>>.env
          echo SNOWPACK_PUBLIC_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}>>.env
          echo SNOWPACK_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}>>.env
          echo SNOWPACK_PUBLIC_TIME_CAPSULE_COLLECTION=time_capsules_dev>>.env
      - name: Build
        run: yarn run build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 7d
          projectId: freshy-the-journey
